#define RRQ_OPCODE 0x01
#define WRQ_OPCODE 0x02
#define DTA_OPCODE 0x03
#define ACK_OPCODE 0x04
#define ERR_OPCODE 0x05

#define NOT_FOUND_ERRCODE 0x1
#define ILLEGAL_OP_ERRCODE 0x4

#define MAX_DATA_SEGMENT_SIZE 512
#define MAX_PKT_SIZE 516
#define MAX_BLOCK_NUM 0xFFFF
#define ACK_PKT_SIZE 4

#define NETASCII_MODE 0
#define OCTET_MODE 1
#define NETASCII_MODE_S "netascii\0"
#define OCTET_MODE_S "octet\0"
#define TRANSFER_MODE_MAX_LEN 10

#define ADDR_STRING_LENGTH 16
